# site settings
name: Eutopian
title: Eutopian
subtitle:
email: eutopian.eu@gmail.com
description: Osservatorio europeo sull'innovazione democratica
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eutopian.eu" # the base hostname & protocol for your site
author:
street_address: Via Umberto Guarnieri 4
city: Roma
state:
zip_code: "00177"
country:
phone:

# social settings
facebook: https://fb.me/eutopian.eu
github: https://github.com/eutopian-eu
instagram: https://www.instagram.com/ass.eutopian/
linkedin: https://www.linkedin.com/company/eutopian/
twitter: https://twitter.com/eutopian_eu

# build settings
markdown: kramdown

menus:
  - Home: "/"
  - Chi Siamo: "/features/chi-siamo.html"
  - Manifesto: "/features/manifesto.html"
  - Statuto: "/features/statuto.html"
  - Diventa Socio: "/features/diventa-socio.html"

sass:
  style: compressed
