# site settings
title: Eutopian
subtitle:
email:
description: Osservatorio europeo sull'innovazione democratica
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eutopian.eu" # the base hostname & protocol for your site
author:
street_address: Via Umberto Guarnieri 4
city: Roma
state:
zip_code: 00177
country:
phone:

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url:
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

menus:
  - Home: "/index.html"
  - Generic: "/generic.html"
  - Elements: "/elements.html"
  - Log in: "#"
  - Sign up: "#"

sass:
  style: compressed
