# site settings
title: Eutopian
subtitle:
email:
description: Osservatorio europeo sull'innovazione democratica
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://eutopian.eu" # the base hostname & protocol for your site
author:
street_address: Via Umberto Guarnieri 4
city: Roma
state:
zip_code: 00177
country:
phone:

# social settings
facebook_url: https://fb.me/eutopian.eu
github_url: https://github.com/eutopian-eu
instagram_url: https://www.instagram.com/ass.eutopian/
linkedin_url: https://www.linkedin.com/company/eutopian/
twitter_url: https://twitter.com/eutopian_eu


# build settings
markdown: kramdown

menus:
  - Home: "/index.html"
  - Generic: "/generic.html"
  - Elements: "/elements.html"
  - Log in: "#"
  - Sign up: "#"

sass:
  style: compressed
